/**
 * Generated Project Schema (LLM Structured Output)
 *
 * WHY ZOD (not class-validator)?
 * ─────────────────────────────
 * We use Zod here because the LLM response is an UNKNOWN JSON blob parsed
 * from a string (`JSON.parse(response.content)`). Zod excels at functional
 * parsing of untrusted data: `.safeParse()` validates AND transforms in one
 * step, returning a typed result or structured errors — no class instantiation
 * needed.
 *
 * Class-validator (used for the HTTP DTO) works differently: it validates
 * class instances created by NestJS's ValidationPipe via `class-transformer`.
 * This requires the NestJS DI pipeline — which doesn't exist when parsing
 * raw LLM output in a BullMQ processor.
 *
 * COERCION STRATEGY
 * ─────────────────
 * LLMs sometimes return `"3"` instead of `3` for numeric fields.
 * We use `z.coerce.number()` for `storyPoints` to silently handle this
 * without crashing the pipeline. This is intentional fault tolerance —
 * the LLM is an unreliable producer, and strict `z.number()` would reject
 * valid-but-misformatted responses.
 *
 * TOKEN CEILING
 * ─────────────
 * Max 4 epics × 7 issues = 28 total issues.
 * This fits within 4096 output tokens. Higher limits cause LLM truncation
 * mid-JSON → `JSON.parse()` crash.
 */

import { z } from 'zod';

// ============================================================
// ENUM SCHEMAS — Mirror existing DB enums exactly
// ============================================================

/**
 * Mirrors `ProjectMethodology` from project-template.entity.ts
 * Values: agile | scrum | kanban | waterfall | hybrid | lean
 */
export const MethodologySchema = z.enum([
  'agile',
  'scrum',
  'kanban',
  'waterfall',
  'hybrid',
  'lean',
]);

/**
 * Mirrors `IssueType` from issue.entity.ts (excluding 'Epic' —
 * Epics are generated as parent issues, not children)
 */
export const IssueTypeSchema = z.enum(['Story', 'Task', 'Bug', 'Sub-task']);

/**
 * Mirrors `IssuePriority` from issue.entity.ts
 */
export const PrioritySchema = z.enum([
  'Highest',
  'High',
  'Medium',
  'Low',
  'Lowest',
]);

// ============================================================
// COMPOSITE SCHEMAS — Nested structure for LLM output
// ============================================================

/**
 * Single issue generated by the LLM.
 * Will be inserted as a child of an Epic via `parentId`.
 */
export const GeneratedIssueSchema = z.object({
  title: z
    .string()
    .min(3, 'Issue title must be at least 3 characters')
    .max(255, 'Issue title must not exceed 255 characters'),

  description: z
    .string()
    .max(2000, 'Issue description must not exceed 2000 characters')
    .optional()
    .default(''),

  type: IssueTypeSchema.default('Task'),

  priority: PrioritySchema.default('Medium'),

  /**
   * COERCION: LLMs sometimes return "3" instead of 3.
   * z.coerce.number() handles this silently — fault tolerance
   * for an unreliable producer (the LLM).
   */
  storyPoints: z.coerce
    .number()
    .int('Story points must be an integer')
    .min(0, 'Story points cannot be negative')
    .max(21, 'Story points cannot exceed 21 (Fibonacci scale)')
    .default(0),

  labels: z
    .array(z.string().max(50, 'Label must not exceed 50 characters'))
    .max(5, 'Maximum 5 labels per issue')
    .default([]),
});

/**
 * Epic generated by the LLM.
 * Will be inserted as an Issue with `type: 'Epic'`.
 * Child issues reference back via `parentId`.
 *
 * MAX 7 ISSUES per epic — Token ceiling constraint.
 */
export const GeneratedEpicSchema = z.object({
  title: z
    .string()
    .min(3, 'Epic title must be at least 3 characters')
    .max(255, 'Epic title must not exceed 255 characters'),

  description: z
    .string()
    .max(2000, 'Epic description must not exceed 2000 characters')
    .optional()
    .default(''),

  issues: z
    .array(GeneratedIssueSchema)
    .min(1, 'Each epic must have at least 1 issue')
    .max(7, 'Maximum 7 issues per epic (token ceiling constraint)'),
});

/**
 * Top-level project generated by the LLM.
 *
 * MAX 4 EPICS — combined with max 7 issues/epic = 28 issues ceiling.
 * This fits within 4096 LLM output tokens.
 *
 * NOTE: Server-injected fields NOT in this schema:
 *   - Project.key (generated from projectName + uniqueness check)
 *   - Project.organizationId (from JWT)
 *   - Issue.projectId (from created Project)
 *   - Issue.parentId (wired in transaction loop)
 *   - Issue.reporterId (from JWT)
 *   - Issue.number (monotonic counter in transaction)
 *   - Issue.statusId / Issue.status (default 'Backlog')
 */
export const GeneratedProjectSchema = z.object({
  projectName: z
    .string()
    .min(2, 'Project name must be at least 2 characters')
    .max(100, 'Project name must not exceed 100 characters'),

  description: z
    .string()
    .max(2000, 'Project description must not exceed 2000 characters')
    .optional()
    .default(''),

  methodology: MethodologySchema.default('agile'),

  epics: z
    .array(GeneratedEpicSchema)
    .min(1, 'Project must have at least 1 epic')
    .max(4, 'Maximum 4 epics per project (token ceiling constraint)'),
});

// ============================================================
// EXPORTED TYPES — Inferred from Zod schemas
// ============================================================

/** Fully typed LLM output after Zod validation */
export type GeneratedProject = z.infer<typeof GeneratedProjectSchema>;

/** Single epic within a generated project */
export type GeneratedEpic = z.infer<typeof GeneratedEpicSchema>;

/** Single issue within a generated epic */
export type GeneratedIssue = z.infer<typeof GeneratedIssueSchema>;

/** Methodology enum values */
export type Methodology = z.infer<typeof MethodologySchema>;

/** Issue type enum values (excluding Epic) */
export type GeneratedIssueType = z.infer<typeof IssueTypeSchema>;

/** Priority enum values */
export type GeneratedPriority = z.infer<typeof PrioritySchema>;
